In [1]:
import numpy as np
import tensorflow as tf

In [2]:
npz = np.load('Audiobooks_data_train.npz')

train_inputs = npz['inputs'].astype(np.float)
train_targets = npz['targets'].astype(np.int)

npz = np.load('Audiobooks_data_validation.npz')
validation_inputs, validation_targets = npz['inputs'].astype(np.float), npz['targets'].astype(np.int)

npz = np.load('Audiobooks_data_test.npz')
test_inputs, test_targets = npz['inputs'].astype(np.float), npz['targets'].astype(np.int)

<ipython-input-2-cb7c10674898>:3: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  train_inputs = npz['inputs'].astype(np.float)
<ipython-input-2-cb7c10674898>:4: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  train_targets = 

In [3]:
#input_size = 10
output_size = 2
hidden_layer_size = 50

model = tf.keras.Sequential([
                            tf.keras.layers.Dense(hidden_layer_size, activation='relu'),
                            tf.keras.layers.Dense(hidden_layer_size, activation='relu'),
                            tf.keras.layers.Dense(output_size, activation='softmax')    
                            ])

model.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics = ['accuracy'])

batch_size = 100

max_epochs=100

early_stopping = tf.keras.callbacks.EarlyStopping(patience=2)

model.fit(train_inputs,
          train_targets,
          batch_size=batch_size,
          epochs=max_epochs,
          callbacks=[early_stopping],
          validation_data=(validation_inputs, validation_targets),
          verbose=2
          )

Epoch 1/100
36/36 - 1s - loss: 0.6122 - accuracy: 0.6477 - val_loss: 0.5182 - val_accuracy: 0.7047 - 992ms/epoch - 28ms/step
Epoch 2/100
36/36 - 0s - loss: 0.4746 - accuracy: 0.7429 - val_loss: 0.4366 - val_accuracy: 0.7584 - 79ms/epoch - 2ms/step
Epoch 3/100
36/36 - 0s - loss: 0.4173 - accuracy: 0.7815 - val_loss: 0.3946 - val_accuracy: 0.8121 - 75ms/epoch - 2ms/step
Epoch 4/100
36/36 - 0s - loss: 0.3875 - accuracy: 0.7910 - val_loss: 0.3795 - val_accuracy: 0.7919 - 95ms/epoch - 3ms/step
Epoch 5/100
36/36 - 0s - loss: 0.3725 - accuracy: 0.7960 - val_loss: 0.3625 - val_accuracy: 0.8121 - 82ms/epoch - 2ms/step
Epoch 6/100
36/36 - 0s - loss: 0.3596 - accuracy: 0.8100 - val_loss: 0.3537 - val_accuracy: 0.8098 - 88ms/epoch - 2ms/step
Epoch 7/100
36/36 - 0s - loss: 0.3518 - accuracy: 0.8083 - val_loss: 0.3550 - val_accuracy: 0.8009 - 81ms/epoch - 2ms/step
Epoch 8/100
36/36 - 0s - loss: 0.3500 - accuracy: 0.8072 - val_loss: 0.3442 - val_accuracy: 0.8054 - 87ms/epoch - 2ms/step
Epoch 9/100
36

In [4]:
test_loss, test_accuracy = model.evaluate(test_inputs, test_targets)

14/14 [==============================] - 0s 2ms/step - loss: 0.3794 - accuracy: 0.7991


In [5]:
print('\nTest loss: {0:.2f}. Test accuracy: {1:.2f}%'.format(test_loss, test_accuracy*100.))


Test loss: 0.38. Test accuracy: 79.91%


In [6]:
model.predict(test_inputs).round(2)

14/14 [==============================] - 0s 2ms/step


array([[0.51, 0.49],
       [1.  , 0.  ],
       [0.41, 0.59],
       [0.31, 0.69],
       [0.  , 1.  ],
       [0.32, 0.68],
       [0.29, 0.71],
       [0.97, 0.03],
       [1.  , 0.  ],
       [0.14, 0.86],
       [0.02, 0.98],
       [0.48, 0.52],
       [0.29, 0.71],
       [0.34, 0.66],
       [0.  , 1.  ],
       [0.14, 0.86],
       [0.54, 0.46],
       [0.13, 0.87],
       [0.  , 1.  ],
       [1.  , 0.  ],
       [0.58, 0.42],
       [0.99, 0.01],
       [0.59, 0.41],
       [0.61, 0.39],
       [0.3 , 0.7 ],
       [0.41, 0.59],
       [0.01, 0.99],
       [1.  , 0.  ],
       [0.44, 0.56],
       [0.15, 0.85],
       [1.  , 0.  ],
       [0.82, 0.18],
       [0.  , 1.  ],
       [0.  , 1.  ],
       [0.55, 0.45],
       [0.54, 0.46],
       [0.43, 0.57],
       [1.  , 0.  ],
       [0.48, 0.52],
       [0.13, 0.87],
       [1.  , 0.  ],
       [0.  , 1.  ],
       [0.  , 1.  ],
       [0.48, 0.52],
       [0.37, 0.63],
       [0.  , 1.  ],
       [0.42, 0.58],
       [1.  ,

In [7]:
model.predict(test_inputs)[:,1].round(0)

14/14 [==============================] - 0s 1ms/step


array([0., 0., 1., 1., 1., 1., 1., 0., 0., 1., 1., 1., 1., 1., 1., 1., 0.,
       1., 1., 0., 0., 0., 0., 0., 1., 1., 1., 0., 1., 1., 0., 0., 1., 1.,
       0., 0., 1., 0., 1., 1., 0., 1., 1., 1., 1., 1., 1., 0., 0., 1., 0.,
       1., 1., 1., 0., 1., 1., 0., 1., 1., 0., 0., 1., 1., 1., 1., 1., 0.,
       0., 1., 0., 1., 0., 0., 1., 1., 0., 1., 1., 1., 1., 1., 1., 0., 1.,
       0., 1., 0., 0., 1., 1., 0., 1., 1., 1., 1., 1., 1., 0., 0., 1., 1.,
       1., 0., 1., 1., 1., 0., 1., 1., 0., 1., 0., 0., 1., 1., 1., 0., 1.,
       1., 0., 1., 0., 1., 0., 1., 0., 1., 1., 1., 0., 1., 0., 1., 1., 1.,
       1., 0., 1., 0., 0., 0., 1., 1., 1., 1., 1., 1., 0., 0., 1., 1., 1.,
       0., 1., 1., 1., 1., 0., 0., 0., 1., 0., 0., 0., 0., 1., 0., 0., 1.,
       1., 1., 0., 1., 1., 0., 0., 1., 1., 1., 0., 0., 1., 1., 1., 1., 0.,
       0., 1., 0., 1., 1., 1., 0., 0., 0., 1., 0., 1., 1., 0., 0., 1., 1.,
       1., 1., 1., 1., 0., 1., 1., 0., 1., 0., 1., 1., 1., 0., 1., 1., 1.,
       0., 0., 1., 1., 0.

In [8]:
np.argmax(model.predict(test_inputs), axis=1)

14/14 [==============================] - 0s 2ms/step


array([0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0,
       0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1,
       1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1,
       1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0,
       0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1,
       0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1,
       0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0,
       1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0,
       0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0,
       1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1,
       1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0,
       1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1,
       1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1,
       1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1,

In [9]:
model.save('audiobooks_model.h5')